### PR TITLE
Fixes #1: AppVeyor CI

### LINKED ISSUE #1: Fix AppVeyor CI script to scan for files and fail build on syntax error
File to fix: `appveyor.yml`

There are two goals:
- For each `.mqh` file (including submodules) run the compiler/syntax checker (e.g. using `metaeditor`).
- When compiler fails to compile one of the files, the whole build script should fail. You can use `forfiles` usually returns all the time the successful build.

Current CI test results can be found in [here](https://ci.appveyor.com/project/kenorb/ea31337-strategies/build/1.0.6).

You can test that as part of the PR, or you can also clone the repo, activate CI tests on your fork and test it.

### PR DESCRIPTION
**Pull request by ghost**
I corrected some problems with the existing AppVeyor file, but now I get errors about file includes. Do you have any idea where these files are supposed to be?

### CODE REVIEW

**Comment by ghost** [comment]
The log can be found here: https://ci.appveyor.com/project/ryu0/ea31337-strategies/build/1.0.1

**Comment by kenorb** [comment]
Can you clone it the same as [Travis CI does](https://travis-ci.org/EA31337/EA31337-strategies/builds/382399899#L423)? So:

```
git clone --depth=50 https://github.com/EA31337/EA31337-strategies.git EA31337/EA31337-strategies
git submodule update --init --recursive
```

Which seems to work for Travis.

**Comment by kenorb** [comment]
Ah, ok, you cloned it right. Sorry, was checking the other log.

**Comment by ghost** [comment]
Yes, it appears to fail because this is a pull request and not a direct commit. I'll see if I can correct that later.

**Comment by kenorb** [comment]
I think that's correct. The task was to make Appveyor fail on the compilation of files which it didn't before. So as far the compilation log file consist of lines with `error` or `warning`, the test should fail.

I'll be working on fixing these files later on, so no worries.

**Comment by kenorb** [comment]
Question, do you really need to clone the repo? Isn't Appveyor already doing it? Or it's a problem with the missing submodules?

**Comment by ghost** [comment]
AppVeyor was already cloning the repo, but it didn't automatically grab the submodules at the same time. I had to do that for there to be any code for metaeditor to compile.

**Comment by ghost** [comment]
The only solution I found was to override the clone method with a script.

**Comment by ghost** [comment]
See here: https://github.com/appveyor/ci/issues/899

**Comment by kenorb** [comment]
Also question, does `findstr "error warning"` includes `error` or `warning` lines? As it's using the phrase together `"error warning"` whereas there are no any lines with `error warning`. So I was wondering whether it'll succeed on no errors.

**Pull request merged**
